version: '2'
services:
    jhexample-app:
        image: jhexample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@jhexample-oracle:1521:JhExample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 4200:4200
